# Generated by Django 5.2.5 on 2025-08-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(max_length=100, unique=True, verbose_name="code"),
                ),
                (
                    "clicks_count",
                    models.PositiveIntegerField(default=0, verbose_name="clicks count"),
                ),
                (
                    "joins_count",
                    models.PositiveIntegerField(default=0, verbose_name="joins count"),
                ),
                (
                    "last_invite_link",
                    models.TextField(
                        blank=True, null=True, verbose_name="last invite link"
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="full_name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                db_index=True, unique=True, verbose_name="telegram_id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="username"
            ),
        ),
        migrations.AlterField(
            model_name="usercontact",
            name="phone_number",
            field=models.CharField(max_length=32, verbose_name="phone number"),
        ),
        migrations.AddField(
            model_name="user",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="bot.source",
                verbose_name="source",
            ),
        ),
    ]
