# Generated by Django 5.2.5 on 2025-08-26 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_source_alter_user_full_name_alter_user_telegram_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="source",
        ),
        migrations.DeleteModel(
            name="Source",
        ),
    ]
