# Generated by Django 5.2.5 on 2025-08-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_remove_user_source_delete_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="UTMSourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=255, verbose_name="source")),
                (
                    "source_type",
                    models.CharField(max_length=255, verbose_name="source type"),
                ),
            ],
            options={
                "verbose_name": "UTM Source Type",
                "verbose_name_plural": "UTM Source Types",
            },
        ),
        migrations.CreateModel(
            name="UTMSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("invite_link", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="bot.utmsourcetype",
                        verbose_name="source type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
