# Generated by Django 5.2.5 on 2025-08-26 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_utmsourcetype_utmsource"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UTMSource",
        ),
    ]
